/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.action;
import java.awt.Image;
import javax.imageio.ImageIO;
import java.io.*;
import java.io.File;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ssh.citizen.Citizen;
import com.ssh.citizen.CitizenDAO;
import com.ssh.common.Global;
import com.ssh.struts.form.AddForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-11-2018
 * 
 * XDoclet definition:
 * @struts.action path="/add" name="addForm" input="/jsp/add.jsp" scope="request" validate="true"
 */
public class AddAction_dwj extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddForm addForm = (AddForm) form;// TODO Auto-generated method stub
		String danyuanNum = addForm.getDanyuanNum();
		String location = addForm.getLocation();
		String name = addForm.getName();
		String photoURL = addForm.getPhotoURL();
		File originalFile = new File(photoURL);
		String newphotoURL =  "E://img//" + danyuanNum + location + name + ".png"; 
		System.out.println(photoURL);
		System.out.println(newphotoURL);
		try {
            File result = new File(newphotoURL);//要写入的图片
            if (result.exists()) {//校验该文件是否已存在
                result.delete();//删除对应的文件，从磁盘中删除
                result = new File(newphotoURL);//只是创建了一个File对象，并没有在磁盘下创建文件
            }
            if (!result.exists()) {//如果文件不存在
                result.createNewFile();//会在磁盘下创建文件，但此时大小为0K
            }
            FileInputStream in = new FileInputStream(originalFile);
            FileOutputStream out = new FileOutputStream(result);// 指定要写入的图片
            int n = 0;// 每次读取的字节长度
            byte[] bb = new byte[1024];// 存储每次读取的内容
            while ((n = in.read(bb)) != -1) {
                out.write(bb, 0, n);// 将读取的内容，写入到输出流当中
            }
            //执行完以上后，磁盘下的该文件才完整，大小是实际大小
            out.close();// 关闭输入输出流
            in.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

		
		
		Citizen instance = new Citizen();
		instance.setDanyuanNum(danyuanNum);
        instance.setLocation(location);
        instance.setName(name);
        instance.setPhotoUrl(photoURL);
        CitizenDAO citizenDAO = (CitizenDAO)Global.getDAO("CitizenDAO");
        List<?> list = citizenDAO.findByExample(instance);
       
        //如果用户存在,则登录成功。
        if(list.size() > 0){
            
            //写入提示信息
            request.setAttribute("message", "该记录已经被注册,请重新输入或者返回" );
            System.out.println("fail");
            return mapping.findForward("addFail");
        }
        citizenDAO.save(instance);
        System.out.println("success");
        request.setAttribute("message", "新增成功:");
        return mapping.findForward("addSuccess");
	}
}