/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.ssh.citizen.Citizen;
import com.ssh.citizen.CitizenDAO;
import com.ssh.common.Global;
import com.ssh.struts.form.AddForm;

/** 
 * MyEclipse Struts
 * Creation date: 09-11-2018
 * 
 * XDoclet definition:
 * @struts.action path="/add" name="addForm" input="/jsp/add.jsp" scope="request" validate="true"
 */
public class AddAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AddForm addForm = (AddForm) form;// TODO Auto-generated method stub
		String danyuanNum = addForm.getDanyuanNum();
		String location = addForm.getLocation();
		String name = addForm.getName();
		String photoURL = addForm.getPhotoURL();
		Citizen instance = new Citizen();
		instance.setDanyuanNum(Long.valueOf(danyuanNum));
        instance.setLocation(location);
        instance.setName(name);
        instance.setPhotoUrl(photoURL);
        CitizenDAO citizenDAO = (CitizenDAO)Global.getDAO("CitizenDAO");
        List<?> list = citizenDAO.findByExample(instance);
       
        //如果用户存在,则登录成功。
        if(list.size() > 0){
            
            //写入提示信息
            request.setAttribute("message", "该记录已经被注册" );
            return mapping.findForward("addFail");
        }
        citizenDAO.save(instance);
        request.setAttribute("message", "新增成功:");
        return mapping.findForward("addSuccess");
	}
}