/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ssh.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.ssh.common.Global;
import com.ssh.struts.form.LoginForm;
import com.ssh.user.User;
import com.ssh.user.UserDAO;
import java.util.List;

/** 
 * MyEclipse Struts
 * Creation date: 09-08-2018
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/jsp/login.jsp" scope="request" validate="true"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
            HttpServletRequest request, HttpServletResponse response) {
        LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
        //获取帐号密码
        String username = loginForm.getUsername();
        String password = loginForm.getPassword();
       
        //检查该用户是否存在
        User instance = new User();
        instance.setUsername(username);
        instance.setPassword(password);
        UserDAO userDAO = (UserDAO)Global.getDAO(UserDAO.TAG);
        List<?> list = userDAO.findByExample(instance);
       
        //如果用户存在,则登录成功。
        if(list.size() > 0){
            User user = (User)list.get(0);
            String nickname = user.getNickname();
            //写入提示信息
            request.setAttribute("message", "您的昵称为:" + nickname);
            return mapping.findForward("loginSuccess");
        }
       
        //不匹配,跳转到登录失败页
        return mapping.findForward("loginFail");
    }
}